// AUTO-GENERATED by scripts/gen-fonts.mjs — do not edit by hand.
// Per-family loaders: FontId → dynamic import of that family's base64.
import type { FontId } from "../library";

export type FontDataMap = Record<string, string>;

export const FONT_LOADERS: Record<FontId, () => Promise<FontDataMap>> = {
  inter: () => import("./inter").then((m) => m.FONT_DATA),
  sourceSerif: () => import("./sourceSerif").then((m) => m.FONT_DATA),
  lora: () => import("./lora").then((m) => m.FONT_DATA),
  playfair: () => import("./playfair").then((m) => m.FONT_DATA),
  plexSans: () => import("./plexSans").then((m) => m.FONT_DATA),
  plexMono: () => import("./plexMono").then((m) => m.FONT_DATA),
};
