// Reads the vendored (subset) TTFs and emits a TS module holding their base64.
// jsPDF needs base64 font data; embedding it in the bundle means PDF generation
// makes ZERO network requests. Re-run with `npm run gen:fonts` if fonts change.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const fontsDir = join(here, "..", "src", "fonts");

const fonts = [
  { id: "interRegular", file: "inter-regular.ttf" },
  { id: "interSemiBold", file: "inter-semibold.ttf" },
  { id: "interBold", file: "inter-bold.ttf" },
  { id: "serifBold", file: "serif-bold.ttf" },
];

let out = `// AUTO-GENERATED by scripts/gen-fonts.mjs — do not edit by hand.\n`;
out += `// Base64 of the subset TTFs, embedded so jsPDF font registration needs no network.\n\n`;
for (const { id, file } of fonts) {
  const b64 = readFileSync(join(fontsDir, file)).toString("base64");
  out += `export const ${id} = "${b64}";\n`;
}

const dest = join(fontsDir, "fontData.ts");
writeFileSync(dest, out);
console.log(`Wrote ${dest} (${(out.length / 1024).toFixed(0)} KB)`);
