// Reads the vendored (subset) TTFs and emits a TS module holding their base64.
// jsPDF needs base64 font data; embedding it in the bundle means PDF generation
// makes ZERO network requests. Re-run with `pnpm gen:fonts` if fonts change.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const fontsDir = join(here, "..", "src", "fonts");

const files = [
  "inter-regular.ttf", "inter-semibold.ttf", "inter-bold.ttf",
  "serif-regular.ttf", "serif-semibold.ttf", "serif-bold.ttf",
  "lora-regular.ttf", "lora-semibold.ttf", "lora-bold.ttf",
  "playfair-regular.ttf", "playfair-semibold.ttf", "playfair-bold.ttf",
  "plexsans-regular.ttf", "plexsans-semibold.ttf", "plexsans-bold.ttf",
  "plexmono-regular.ttf", "plexmono-semibold.ttf", "plexmono-bold.ttf",
];

let out = `// AUTO-GENERATED by scripts/gen-fonts.mjs — do not edit by hand.\n`;
out += `// Base64 of the subset TTFs, keyed by file name, embedded so jsPDF font\n`;
out += `// registration needs no network.\n\n`;
out += `export const FONT_DATA: Record<string, string> = {\n`;
for (const file of files) {
  const b64 = readFileSync(join(fontsDir, file)).toString("base64");
  out += `  ${JSON.stringify(file)}: ${JSON.stringify(b64)},\n`;
}
out += `};\n`;

const dest = join(fontsDir, "fontData.ts");
writeFileSync(dest, out);
console.log(`Wrote ${dest} (${(out.length / 1024).toFixed(0)} KB)`);
