// Reads the vendored (subset) TTFs and emits, PER FAMILY, a TS module holding
// that family's base64 — plus a loader index that maps each FontId to a bare
// dynamic import of its module. jsPDF needs base64 font data; embedding it means
// PDF generation makes ZERO network requests. Splitting per family means the PDF
// path only downloads the base64 for the families a given résumé actually uses
// (see src/fonts/registerFonts.ts). Re-run with `pnpm gen:fonts` if fonts change.
import { readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const fontsDir = join(here, "..", "src", "fonts");
const outDir = join(fontsDir, "fontData");

// Keyed by FontId (must match src/fonts/library.ts). Each value is the family's
// weight files; the module is emitted as fontData/<FontId>.ts. Keeping the key
// equal to the FontId lets the loader index below wire id → import() directly.
const FAMILIES = {
  inter: ["inter-regular.ttf", "inter-semibold.ttf", "inter-bold.ttf"],
  sourceSerif: ["serif-regular.ttf", "serif-semibold.ttf", "serif-bold.ttf"],
  lora: ["lora-regular.ttf", "lora-semibold.ttf", "lora-bold.ttf"],
  playfair: ["playfair-regular.ttf", "playfair-semibold.ttf", "playfair-bold.ttf"],
  plexSans: ["plexsans-regular.ttf", "plexsans-semibold.ttf", "plexsans-bold.ttf"],
  plexMono: ["plexmono-regular.ttf", "plexmono-semibold.ttf", "plexmono-bold.ttf"],
};

const banner = `// AUTO-GENERATED by scripts/gen-fonts.mjs — do not edit by hand.\n`;

// Fresh directory so a removed family can't leave a stale module behind.
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

let totalBytes = 0;
for (const [id, files] of Object.entries(FAMILIES)) {
  let out = banner;
  out += `// Base64 of the ${id} subset TTFs, keyed by file name.\n\n`;
  out += `export const FONT_DATA: Record<string, string> = {\n`;
  for (const file of files) {
    const b64 = readFileSync(join(fontsDir, file)).toString("base64");
    out += `  ${JSON.stringify(file)}: ${JSON.stringify(b64)},\n`;
  }
  out += `};\n`;
  writeFileSync(join(outDir, `${id}.ts`), out);
  totalBytes += out.length;
}

// The loader index. Each entry is a BARE dynamic import of one family module, so
// Rollup/Vite emits it as its own chunk — the PDF path awaits only the used ones.
let index = banner;
index += `// Per-family loaders: FontId → dynamic import of that family's base64.\n`;
index += `import type { FontId } from "../library";\n\n`;
index += `export type FontDataMap = Record<string, string>;\n\n`;
index += `export const FONT_LOADERS: Record<FontId, () => Promise<FontDataMap>> = {\n`;
for (const id of Object.keys(FAMILIES)) {
  index += `  ${id}: () => import("./${id}").then((m) => m.FONT_DATA),\n`;
}
index += `};\n`;
writeFileSync(join(outDir, "index.ts"), index);

console.log(
  `Wrote ${Object.keys(FAMILIES).length} family modules + index to ${outDir} ` +
    `(${(totalBytes / 1024).toFixed(0)} KB total)`,
);
